using System.Text;

namespace TrackMechReviseTool.Core;

public sealed class ChemkinMechanismWriter
{
    private const int SpeciesPerLine = 8;
    private const double RateComparisonTolerance = 1e-12;
    private readonly ReactionEquationParser equationParser = new();

    public void Write(
        string path,
        OutMechanism mechanism,
        ReactionRewritePlanValidationResult validationResult)
    {
        ChemkinReactionSectionWriter.EnsurePlanCanBeWritten(validationResult);
        ValidatePlanSources(mechanism, validationResult.NormalizedRows);

        var selectedByReaction = validationResult.NormalizedRows
            .Where(row => row.Selected)
            .OrderBy(row => row.CandidateIndex)
            .GroupBy(row => row.SourceReactionIndex)
            .ToDictionary(group => group.Key, group => group.ToArray());
        var speciesNames = BuildSpeciesList(mechanism, validationResult.NormalizedRows);
        var builder = new StringBuilder();

        builder.AppendLine("! Generated by TrackMechReviseTool from the parsed .out mechanism.");
        builder.AppendLine("! Original reactions are retained; confirmed marked reactions follow their source reaction.");
        builder.AppendLine("ELEMENTS");
        AppendWrappedNames(builder, mechanism.Elements.Select(element => element.Symbol));
        builder.AppendLine("END");
        builder.AppendLine();
        builder.AppendLine("SPECIES");
        AppendWrappedNames(builder, speciesNames);
        builder.AppendLine("END");
        builder.AppendLine();
        builder.AppendLine("REACTIONS");
        builder.AppendLine();

        foreach (var reaction in mechanism.Reactions.OrderBy(reaction => reaction.Index))
        {
            builder.Append("! Original reaction ").AppendLine(reaction.Index.ToString(System.Globalization.CultureInfo.InvariantCulture));
            ChemkinReactionSectionWriter.AppendSourceReaction(builder, reaction);

            if (!selectedByReaction.TryGetValue(reaction.Index, out var markedRows))
            {
                continue;
            }

            foreach (var row in markedRows)
            {
                builder.Append("! Marked candidate ")
                    .Append(row.CandidateIndex.ToString(System.Globalization.CultureInfo.InvariantCulture))
                    .Append(" from reaction ")
                    .AppendLine(reaction.Index.ToString(System.Globalization.CultureInfo.InvariantCulture));
                ChemkinReactionSectionWriter.AppendMarkedReaction(
                    builder,
                    reaction,
                    row,
                    includeSourceComment: false);
            }
        }

        builder.AppendLine("END");
        File.WriteAllText(path, builder.ToString(), new UTF8Encoding(false));
    }

    private IReadOnlyList<string> BuildSpeciesList(
        OutMechanism mechanism,
        IReadOnlyList<ReactionRewritePlanRow> rows)
    {
        var speciesNames = mechanism.Species.Select(species => species.Name).ToList();
        var knownSpecies = speciesNames.ToHashSet(StringComparer.OrdinalIgnoreCase);

        foreach (var row in rows.Where(row => row.Selected).OrderBy(row => row.SourceReactionIndex).ThenBy(row => row.CandidateIndex))
        {
            var equation = equationParser.Parse(row.CandidateEquation);
            foreach (var participant in equation.Reactants.Concat(equation.Products))
            {
                if (knownSpecies.Add(participant.SpeciesName))
                {
                    speciesNames.Add(participant.SpeciesName);
                }
            }
        }

        return speciesNames;
    }

    private static void ValidatePlanSources(
        OutMechanism mechanism,
        IReadOnlyList<ReactionRewritePlanRow> rows)
    {
        var reactionsByIndex = mechanism.Reactions.ToDictionary(reaction => reaction.Index);
        foreach (var row in rows)
        {
            if (!reactionsByIndex.TryGetValue(row.SourceReactionIndex, out var reaction))
            {
                throw new InvalidOperationException(
                    $"Source reaction {row.SourceReactionIndex} does not exist in the parsed .out mechanism.");
            }
            if (!string.Equals(row.SourceEquation, reaction.Equation, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    $"Reaction {row.SourceReactionIndex} equation in the rewrite plan does not match the .out mechanism.");
            }
            if (!NearlyEqual(row.SourceA, reaction.Rate.A) ||
                !NearlyEqual(row.SourceN, reaction.Rate.B) ||
                !NearlyEqual(row.SourceE, reaction.Rate.Ea))
            {
                throw new InvalidOperationException(
                    $"Reaction {row.SourceReactionIndex} source A, n or E in the rewrite plan does not match the .out mechanism.");
            }
        }
    }

    private static bool NearlyEqual(double left, double right)
    {
        var scale = Math.Max(1.0, Math.Max(Math.Abs(left), Math.Abs(right)));
        return Math.Abs(left - right) <= RateComparisonTolerance * scale;
    }

    private static void AppendWrappedNames(StringBuilder builder, IEnumerable<string> names)
    {
        var lineCount = 0;
        foreach (var name in names)
        {
            if (lineCount == SpeciesPerLine)
            {
                builder.AppendLine();
                lineCount = 0;
            }

            builder.Append(name.PadRight(12));
            lineCount++;
        }

        if (lineCount > 0)
        {
            builder.AppendLine();
        }
    }
}
