using System.Text;

namespace TrackMechReviseTool.Core;

public sealed record MarkedThermoWriteResult(
    int SourceEntryCount,
    IReadOnlyList<string> AddedSpecies);

public sealed class MarkedThermoWriter
{
    private const int SpeciesFieldWidth = 18;
    private readonly ReactionEquationParser equationParser = new();

    public MarkedThermoWriteResult Write(
        string path,
        ThermoDocument sourceThermo,
        OutMechanism mechanism,
        ReactionRewritePlanValidationResult validationResult,
        string elementSymbol)
    {
        ChemkinReactionSectionWriter.EnsurePlanCanBeWritten(validationResult);

        var missingOriginalSpecies = mechanism.Species
            .Select(species => species.Name)
            .Where(speciesName => !sourceThermo.Entries.ContainsKey(speciesName))
            .ToArray();
        if (missingOriginalSpecies.Length > 0)
        {
            throw new InvalidOperationException(
                $"Thermodynamic file is missing original mechanism species: {string.Join(", ", missingOriginalSpecies)}.");
        }

        var sourceByMarkedSpecies = new TraceRuleCatalog()
            .GetRules(mechanism, elementSymbol)
            .SelectMany(rule => rule.States.Select(state => new
            {
                MarkedSpecies = state.Name,
                SourceSpecies = rule.SourceSpecies
            }))
            .ToDictionary(item => item.MarkedSpecies, item => item.SourceSpecies, StringComparer.OrdinalIgnoreCase);
        var originalSpecies = mechanism.Species
            .Select(species => species.Name)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        var requiredMarkedSpecies = FindRequiredMarkedSpecies(validationResult.NormalizedRows, originalSpecies);
        var additions = new List<(string MarkedSpecies, ThermoEntry SourceEntry)>();

        foreach (var markedSpecies in requiredMarkedSpecies)
        {
            if (sourceThermo.Entries.ContainsKey(markedSpecies))
            {
                continue;
            }
            if (!sourceByMarkedSpecies.TryGetValue(markedSpecies, out var sourceSpecies))
            {
                throw new InvalidOperationException(
                    $"Marked species '{markedSpecies}' has no {elementSymbol} trace rule for thermodynamic inheritance.");
            }
            if (!sourceThermo.Entries.TryGetValue(sourceSpecies, out var sourceEntry))
            {
                throw new InvalidOperationException(
                    $"Thermodynamic source entry '{sourceSpecies}' required by '{markedSpecies}' was not found.");
            }

            additions.Add((markedSpecies, sourceEntry));
        }

        var builder = new StringBuilder();
        for (var index = 0; index < sourceThermo.EndLineIndex; index++)
        {
            builder.AppendLine(sourceThermo.Lines[index]);
        }

        if (additions.Count > 0)
        {
            builder.AppendLine("! Marked species generated by TrackMechReviseTool; NASA coefficients inherit from the source species.");
            foreach (var addition in additions)
            {
                builder.Append("! ")
                    .Append(addition.MarkedSpecies)
                    .Append(" inherits thermodynamic coefficients from ")
                    .AppendLine(addition.SourceEntry.SpeciesName);
                AppendRenamedEntry(builder, addition.MarkedSpecies, addition.SourceEntry);
            }
        }

        builder.AppendLine("END");
        foreach (var line in sourceThermo.Lines.Skip(sourceThermo.EndLineIndex + 1))
        {
            builder.AppendLine(line);
        }

        File.WriteAllText(path, builder.ToString(), new UTF8Encoding(false));
        return new MarkedThermoWriteResult(
            sourceThermo.Entries.Count,
            additions.Select(addition => addition.MarkedSpecies).ToArray());
    }

    private IReadOnlyList<string> FindRequiredMarkedSpecies(
        IReadOnlyList<ReactionRewritePlanRow> rows,
        IReadOnlySet<string> originalSpecies)
    {
        var requiredSpecies = new List<string>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var row in rows.Where(row => row.Selected).OrderBy(row => row.SourceReactionIndex).ThenBy(row => row.CandidateIndex))
        {
            var equation = equationParser.Parse(row.CandidateEquation);
            foreach (var participant in equation.Reactants.Concat(equation.Products))
            {
                if (!originalSpecies.Contains(participant.SpeciesName) && seen.Add(participant.SpeciesName))
                {
                    requiredSpecies.Add(participant.SpeciesName);
                }
            }
        }

        return requiredSpecies;
    }

    private static void AppendRenamedEntry(StringBuilder builder, string markedSpecies, ThermoEntry sourceEntry)
    {
        if (markedSpecies.Length > SpeciesFieldWidth)
        {
            throw new InvalidOperationException(
                $"Marked species name '{markedSpecies}' exceeds the {SpeciesFieldWidth}-character NASA name field.");
        }

        builder.Append(markedSpecies.PadRight(SpeciesFieldWidth))
            .AppendLine(sourceEntry.Lines[0][SpeciesFieldWidth..]);
        foreach (var coefficientLine in sourceEntry.Lines.Skip(1))
        {
            builder.AppendLine(coefficientLine);
        }
    }
}
